feat: add trackChanges and Constraints
FlatFilers/flatfile-docs-kitchen-sink pull request #27
Opened 2023-11-06 21:26 UTC by madaley1

2023-11-06 22:12 UTC, ashleygmulligan2 requested changes

2023-11-06 22:12 UTC, ashleygmulligan2 commented on typescript/dynamic-configurations/index.ts
> +                constraints: [
i don't think this is available on workbook level yet, just sheet

2023-11-07 15:30 UTC, madaley1 commented
Associated PR with updates for this PR:
https://github.com/FlatFilers/Platform/pull/5765

2023-11-09 14:19 UTC, ashleygmulligan2 approved these changes

2023-11-09 21:59 UTC, merged